.\" -*- nroff -*-
.TH TEGSERVER 6 "September 2, 2001"
.SH "NAME"
tegserver \- Tenes Empanadas Graciela server
.SH "SYNOPSIS"
.B tegserver
[\fIoptions\fR]
.SH "DESCRIPTION"
.TP
\fB\-h\fR, \fB\-\-help\fR
Print a summary of the options
.TP
\fB\-p\fR, \fB\-\-port\fR PORT
Bind the server to port PORT (default 2000)
.TP
\fB\-s\fR, \fB\-\-seed\fR SEED
New seed for random
.TP
\fB\-v\fR, \fB\-\-version\fR
Print the version number
.TP
\fB\-c\fR, \fB\-\-console\fR BOOLEAN
Enable the console or not (default 1)
.TP
\fB\-g\fR, \fB\-\-ggz\fR
Enable the GGZ mode (default OFF)
.SH AUTHOR
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
This manual page was written by Davide Puricelli <evo@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
